// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjYZFu6lUucubkrAbLKhOvzC3WYau-74',
    appId: '1:61227032022:web:b68b3372d9987575f9d877',
    messagingSenderId: '61227032022',
    projectId: 'corp-doc-ai',
    authDomain: 'corp-doc-ai.firebaseapp.com',
    storageBucket: 'corp-doc-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZUcd-6cEacH8mwQhvBRfANHdERENcP4',
    appId: '1:61227032022:android:b34c29c2a443edb3f9d877',
    messagingSenderId: '61227032022',
    projectId: 'corp-doc-ai',
    storageBucket: 'corp-doc-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaxzueSnXX0WMvKABosnCpAxKl-W4zIQ',
    appId: '1:61227032022:ios:eb934c8e0e7989c1f9d877',
    messagingSenderId: '61227032022',
    projectId: 'corp-doc-ai',
    storageBucket: 'corp-doc-ai.firebasestorage.app',
    iosClientId: '61227032022-skd3pia39g9dkbls4d1dacq17q834bkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.corpDocAi',
  );
}
